// Icons/AllIcons.tsx - All icons

import React from 'react'
import styled from 'styled-components'
import * as R from 'ramda'

import {
  // appendIconImport

  NewTabIcon,
  ImpersonateIcon,
  AddErrataIcon,
  HeartContainedIcon,
  HeartOutlinedIcon,
  SupportTabIcon,
  OnboardingIcon,
  CommunityIcon,
  StatusPageIcon,
  VideoTutorialsIcon,
  AddBookmarkIcon,
  AddDocumentIcon,
  AddPageIcon,
  ArchiveLockIcon,
  EditBookIcon,
  ToDoListIcon,
  ChecklistIcon,
  ExplodingBrainIcon,
  IndentLeftIcon,
  IndentRightIcon,
  StarIcon,
  DotMenuIcon,
  CrownIcon,
  HighlighterIcon,
  MinusContainedIcon,
  ImageOutlinedIcon,
  ChatIcon,
  CrackerIcon,
  NewSectionIcon,
  FlashcardIcon,
  QuestionIcon,
  CalendarIcon,
  FlagOutlinedIcon,
  CorrectAnswersIcon,
  YourScoreIcon,
  TargetScoreIcon,
  PercentileRankIcon,
  QuestionCircleIcon,
  AddIcon,
  ArrowDownIcon,
  ArrowRightIcon,
  BookChartIcon,
  BookIcon,
  ClockIcon,
  CloseIcon,
  EyeIcon,
  HideIcon,
  ListIcon,
  StudentIcon,
  TrashIcon,
  UserIcon,
  SuccessIcon,
  InfoIcon,
  WarningIcon,
  WarningReversed,
  UsersIcon,
  EditIcon,
  PlayIcon,
  PauseIcon,
  StopIcon,
  PlusIcon,
  ScoreIcon,
  ArrowUpFilledIcon,
  ArrowDownFilledIcon,
  MCATIcon,
  McatForChartIcon,
  MiniMCATIcon,
  FlagIcon,
  SelectIcon,
  LineIcon,
  LogoutIcon,
  PolygonIcon,
  CircleIcon,
  PaletteIcon,
  ImageIcon,
  TextIcon,
  UndoIcon,
  RedoIcon,
  DownloadIcon,
  SaveIcon,
  ToggleIcon,
  ExcelIcon,
  OtherExamIcon,
  EditorImageIcon,
  EditorHighlightIcon,
  ToMuchInformationIcon,
  VideoIcon,
  ClinicalContextIcon,
  MCATThinkIcon,
  ScannerIcon,
  GlossaryIcon,
  ResizeIcon,
  SaltyBucksIcon,
  SaltyBucksCalendarIcon,
  SaltyBucksCounterIcon,
  ReloadIcon,
  SubtractIcon,
  BoxClosedIcon,
  AttachmentIcon,
  PreviewIcon,
  VideoCameraIcon,
  ExamEditorIcon,
  StudentContainedIcon,
  CoursesIcon,
  GlossaryContainedIcon,
  BooksContainedIcon,
  FlashcardsIcon,
  WalletsIcon,
  GearIcon,
  NavArrowLeftIcon,
  NavArrowRightIcon,
  NavArrowUpIcon,
  NavArrowDownIcon,
  DashboardIcon,
  GamesIcon,
  NotesIcon,
  VideoPreviewIcon,
  ProjectionsIcon,
  DragIcon,
  ContentQuestionsIcon,
  CloseContainedIcon,
  CheckmarkContainedIcon,
  FlipIcon,
  OpenBookIcon,
  SpeakerMuteIcon,
  SpeakerQuietIcon,
  SpeakerLoudIcon,
  CorrectMarkIcon,
  PersonIcon,
  ScoreFileIcon,
  PlayInCircleIcon,
  PlayInSquaresIcon,
  TotalProgressIcon,
  ChartIcon,
  ShowIcon,
  AddContainedIcon,
  InfoCircleIcon,
  ContentQuestionsOutlineIcon,
  ScissorsIcon,
  BookMarkIcon,
  RestoreIcon,
  PinIcon,
  ProfileIcon,
  AddToBoxIcon,
  AddToArchiveIcon,
  PadlockLockedIcon,
  PadlockOpenIcon,
  FirstPlaceMedalIcon,
  SecondPlaceMedalIcon,
  ThirdPlaceMedalIcon,
  TrophyIcon,
  BookEditorIcon,
  CopyIcon,
  SettingsIcon,
  NotificationBellIcon,
  ErrataIcon,
  RocketIcon,
  NoteIcon,
  ReorderIcon,
  ResetIcon
} from './'

const IconContainer = styled.div`
  display: flex;
  margin-bottom: 16px;
  flex-flow: row;
  align-items: center;

  p {
    margin-right: 8px;
  }
`

const AllIcons = () => {
  const icons = [
    // appendIconComponent

    { component: NewTabIcon, title: 'NewTabIcon' },
    { component: ImpersonateIcon, title: 'ImpersonateIcon' },
    { component: AddErrataIcon, title: 'AddErrataIcon' },
    { component: HeartContainedIcon, title: 'HeartContainedIcon' },
    { component: HeartOutlinedIcon, title: 'HeartOutlinedIcon' },
    { component: SupportTabIcon, title: 'SupportTabIcon' },
    { component: OnboardingIcon, title: 'OnboardingIcon' },
    { component: CommunityIcon, title: 'CommunityIcon' },
    { component: StatusPageIcon, title: 'StatusPageIcon' },
    { component: VideoTutorialsIcon, title: 'VideoTutorialsIcon' },
    { component: AddBookmarkIcon, title: 'AddBookmarkIcon' },
    { component: AddDocumentIcon, title: 'AddDocumentIcon' },
    { component: AddPageIcon, title: 'AddPageIcon' },
    { component: ArchiveLockIcon, title: 'ArchiveLockIcon' },
    { component: EditBookIcon, title: 'EditBookIcon' },
    { component: ToDoListIcon, title: 'ToDoListIcon' },
    { component: ChecklistIcon, title: 'ChecklistIcon' },
    { component: ExplodingBrainIcon, title: 'ExplodingBrainIcon' },
    { component: IndentLeftIcon, title: 'IndentLeftIcon' },
    { component: IndentRightIcon, title: 'IndentRightIcon' },
    { component: StarIcon, title: 'StarIcon' },
    { component: DotMenuIcon, title: 'DotMenuIcon' },
    { component: CrownIcon, title: 'CrownIcon' },
    { component: HighlighterIcon, title: 'HighlighterIcon' },
    { component: MinusContainedIcon, title: 'MinusContainedIcon' },
    { component: ImageOutlinedIcon, title: 'ImageOutlinedIcon' },
    { component: ChatIcon, title: 'ChatIcon' },
    { component: CrackerIcon, title: 'CrackerIcon' },
    { component: NewSectionIcon, title: 'NewSectionIcon' },
    { component: FlashcardIcon, title: 'FlashcardIcon' },
    { component: QuestionIcon, title: 'QuestionIcon' },
    { component: CalendarIcon, title: 'CalendarIcon' },
    { component: FlagOutlinedIcon, title: 'FlagOutlinedIcon' },
    { component: CorrectAnswersIcon, title: 'CorrectAnswersIcon' },
    { component: YourScoreIcon, title: 'YourScoreIcon' },
    { component: TargetScoreIcon, title: 'TargetScoreIcon' },
    { component: PercentileRankIcon, title: 'PercentileRankIcon' },
    { component: QuestionCircleIcon, title: 'QuestionCircleIcon' },
    { component: AddIcon, title: 'AddIcon' },
    { component: ArrowDownIcon, title: 'ArrowDownIcon' },
    { component: ArrowRightIcon, title: 'ArrowRightIcon' },
    { component: BookChartIcon, title: 'BookChartIcon' },
    { component: BookIcon, title: 'BookIcon' },
    { component: ClockIcon, title: 'ClockIcon' },
    { component: CloseIcon, title: 'CloseIcon' },
    { component: EyeIcon, title: 'EyeIcon' },
    { component: HideIcon, title: 'HideIcon' },
    { component: ListIcon, title: 'ListIcon' },
    { component: StudentIcon, title: 'StudentIcon' },
    { component: TrashIcon, title: 'TrashIcon' },
    { component: UserIcon, title: 'UserIcon' },
    { component: SuccessIcon, title: 'SuccessIcon' },
    { component: InfoIcon, title: 'InfoIcon' },
    { component: WarningIcon, title: 'WarningIcon' },
    { component: WarningReversed, title: 'WarningReversed' },
    { component: UsersIcon, title: 'UsersIcon' },
    { component: EditIcon, title: 'EditIcon' },
    { component: PlayIcon, title: 'PlayIcon' },
    { component: PauseIcon, title: 'PauseIcon' },
    { component: StopIcon, title: 'StopIcon' },
    { component: PlusIcon, title: 'PlusIcon' },
    { component: ScoreIcon, title: 'ScoreIcon' },
    { component: ArrowUpFilledIcon, title: 'ArrowUpFilledIcon' },
    { component: ArrowDownFilledIcon, title: 'ArrowDownFilledIcon' },
    { component: MCATIcon, title: 'MCATIcon' },
    { component: McatForChartIcon, title: 'McatForChartIcon' },
    { component: MiniMCATIcon, title: 'MiniMCATIcon' },
    { component: FlagIcon, title: 'FlagIcon' },
    { component: SelectIcon, title: 'SelectIcon' },
    { component: LineIcon, title: 'LineIcon' },
    { component: LogoutIcon, title: 'LogoutIcon' },
    { component: PolygonIcon, title: 'PolygonIcon' },
    { component: CircleIcon, title: 'CircleIcon' },
    { component: PaletteIcon, title: 'PaletteIcon' },
    { component: ImageIcon, title: 'ImageIcon' },
    { component: TextIcon, title: 'TextIcon' },
    { component: UndoIcon, title: 'UndoIcon' },
    { component: RedoIcon, title: 'RedoIcon' },
    { component: DownloadIcon, title: 'DownloadIcon' },
    { component: SaveIcon, title: 'SaveIcon' },
    { component: ToggleIcon, title: 'ToggleIcon' },
    { component: ExcelIcon, title: 'ExcelIcon' },
    { component: OtherExamIcon, title: 'OtherExamIcon' },
    { component: EditorImageIcon, title: 'EditorImageIcon' },
    { component: EditorHighlightIcon, title: 'EditorHighlightIcon' },
    { component: ToMuchInformationIcon, title: 'ToMuchInformationIcon' },
    { component: VideoIcon, title: 'VideoIcon' },
    { component: ClinicalContextIcon, title: 'ClinicalContextIcon' },
    { component: MCATThinkIcon, title: 'MCATThinkIcon' },
    { component: ScannerIcon, title: 'Scanner' },
    { component: GlossaryIcon, title: 'GlossaryIcon' },
    { component: ResizeIcon, title: 'ResizeIcon' },
    { component: SaltyBucksIcon, title: 'SaltyBucksIcon' },
    { component: SaltyBucksCalendarIcon, title: 'SaltyBucksCalendarIcon' },
    { component: SaltyBucksCounterIcon, title: 'SaltyBucksCounterIcon' },
    { component: ReloadIcon, title: 'ReloadIcon' },
    { component: SubtractIcon, title: 'SubtractIcon' },
    { component: BoxClosedIcon, title: 'BoxClosedIcon' },
    { component: AttachmentIcon, title: 'AttachmentIcon' },
    { component: PreviewIcon, title: 'PreviewIcon' },
    { component: ExamEditorIcon, title: 'ExamEditorIcon' },
    { component: StudentContainedIcon, title: 'StudentContainedIcon' },
    { component: CoursesIcon, title: 'CoursesIcon' },
    { component: GlossaryContainedIcon, title: 'GlossaryContainedIcon' },
    { component: BooksContainedIcon, title: 'BooksContainedIcon' },
    { component: FlashcardsIcon, title: 'FlashcardsIcon' },
    { component: WalletsIcon, title: 'WalletsIcon' },
    { component: VideoCameraIcon, title: 'VideoCameraIcon' },
    { component: NavArrowRightIcon, title: 'NavArrowRightIcon' },
    { component: NavArrowLeftIcon, title: 'NavArrowLeftIcon' },
    { component: NavArrowUpIcon, title: 'NavArrowUpIcon' },
    { component: NavArrowDownIcon, title: 'NavArrowDownIcon' },
    { component: GearIcon, title: 'GearIcon' },
    { component: DashboardIcon, title: 'DashboardIcon' },
    { component: GamesIcon, title: 'GamesIcon' },
    { component: NotesIcon, title: 'NotesIcon' },
    { component: VideoPreviewIcon, title: 'VideoPreviewIcon' },
    { component: ProjectionsIcon, title: 'ProjectionsIcon' },
    { component: DragIcon, title: 'DragIcon' },
    { component: ContentQuestionsIcon, title: 'ContentQuestionsIcon' },
    {
      component: ContentQuestionsOutlineIcon,
      title: 'ContentQuestionsOutlineIcon'
    },
    { component: CloseContainedIcon, title: 'CloseContainedIcon' },
    { component: CheckmarkContainedIcon, title: 'CheckmarkContainedIcon' },
    { component: FlipIcon, title: 'FlipIcon' },
    { component: OpenBookIcon, title: 'OpenBookIcon' },
    { component: SpeakerMuteIcon, title: 'SpeakerMuteIcon' },
    { component: SpeakerQuietIcon, title: 'SpeakerQuietIcon' },
    { component: SpeakerLoudIcon, title: 'SpeakerLoudIcon' },
    { component: CorrectMarkIcon, title: 'CorrectMark' },
    { component: PersonIcon, title: 'Person' },
    { component: ProfileIcon, title: 'Profile' },
    { component: ScoreFileIcon, title: 'ScoreFile' },
    { component: PlayInCircleIcon, title: 'PlayInCircle' },
    { component: PlayInSquaresIcon, title: 'PlayInSquares' },
    { component: TotalProgressIcon, title: 'TotalProgress' },
    { component: ChartIcon, title: 'Chart' },
    { component: ShowIcon, title: 'Show' },
    { component: AddContainedIcon, title: 'AddContainedIcon' },
    { component: InfoCircleIcon, title: 'InfoCircleIcon' },
    { component: ScissorsIcon, title: 'Scissors' },
    { component: BookMarkIcon, title: 'BookMark' },
    { component: RestoreIcon, title: 'RestoreIcon' },
    { component: PinIcon, title: 'PinIcon' },
    { component: AddToBoxIcon, title: 'AddToBoxIcon' },
    { component: AddToArchiveIcon, title: 'AddToArchiveIcon' },
    { component: PadlockLockedIcon, title: 'PadlockLockedIcon' },
    { component: PadlockOpenIcon, title: 'PadlockOpenIcon' },
    { component: FirstPlaceMedalIcon, title: 'FirstPlaceMedalIcon' },
    { component: SecondPlaceMedalIcon, title: 'SecondPlaceMedalIcon' },
    { component: ThirdPlaceMedalIcon, title: 'ThirdPlaceMedalIcon' },
    { component: TrophyIcon, title: 'TrophyIcon' },
    { component: BookEditorIcon, title: 'BookEditorIcon' },
    { component: CopyIcon, title: 'CopyIcon' },
    { component: SettingsIcon, title: 'SettingsIcon' },
    { component: NotificationBellIcon, title: 'NotificationBellIcon' },
    { component: ErrataIcon, title: 'ErrataIcon' },
    { component: RocketIcon, title: 'RocketIcon' },
    { component: NoteIcon, title: 'NoteIcon' },
    { component: ReorderIcon, title: 'ReorderIcon' },
    { component: ResetIcon, title: 'ResetIcon' }
  ]

  const sortedIcons = R.sortBy(R.prop('title'))(icons)

  return (
    <IconsContainer>
      {sortedIcons.map(
        ({ component: I, title }, i: number): JSX.Element => (
          <IconContainer key={i}>
            <p>{`${title}:`}</p>
            <I />
          </IconContainer>
        )
      )}
    </IconsContainer>
  )
}

AllIcons.defaultProps = {}

const IconsContainer = styled.div`
  svg {
    font-size: 20px;
  }
`

export default AllIcons
