version: '2'
services:
  lb:
    scale: 1
    start_on_create: true
    lb_config:
      port_rules:
        - hostname: $HOSTNAME
          protocol: http
          source_port: 80
          target_port: 80
          selector: web.container.target=$CI_PROJECT_PATH_SLUG.$CI_ENV
  web:
    scale: 1
    start_on_create: true
    drain_timeout_ms: 10000
  web-roll:
    scale: 0
    start_on_create: false
    drain_timeout_ms: 10000